pluginManagement {
    repositories {
        if (System.getenv('GITHUB_ACTIONS') == 'true') {
            google()
            mavenCentral()
            gradlePluginPortal()
            maven { url 'https://maven.aliyun.com/repository/google' }
            maven { url 'https://maven.aliyun.com/repository/central' }
        } else {
            gradlePluginPortal()
            maven { url 'https://maven.aliyun.com/repository/google' }
            maven { url 'https://maven.aliyun.com/repository/central' }
            google()
            mavenCentral()
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        if (System.getenv('GITHUB_ACTIONS') == 'true') {
            google()
            mavenCentral()
            maven { url 'https://jitpack.io' }
            maven { url 'https://maven.aliyun.com/repository/google' }
            maven { url 'https://maven.aliyun.com/repository/central' }
            maven { url 'https://maven.aliyun.com/repository/public' }
        } else {
            maven { url 'https://maven.aliyun.com/repository/google' }
            maven { url 'https://maven.aliyun.com/repository/central' }
            maven { url 'https://maven.aliyun.com/repository/public' }
            maven { url 'https://jitpack.io' }
            google()
            mavenCentral()
        }
    }
}
rootProject.name = 'LightlyMonitor'
include ':app'
